package main

import (
	"iitu/swagger-example/handler"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "iitu/swagger-example/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example
// @version 1.0
// @description Sample server for Halyk-IITU Go course
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email aburavov189@gmail.com

// @host localhost:8081
// @BasePath /

func main() {
	r := gin.Default()
	url := ginSwagger.URL("http://localhost:8081/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	r.GET("/user/:id", handler.GetUser)
	r.POST("/user", handler.UpdateUser)

	r.Run(":8081")
}
